name = "latent-server-alt"
main = "src/index.ts"
compatibility_date = "2024-03-04"
account_id = "2612967e82750619224e7446c4c41b0b"

[[d1_databases]]
binding = "DB"
database_name = "latent-db-alt"
database_id = "6888a906-0f94-4d15-b6eb-a5ca280c3954"
