name = "latent-server"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "latent-db"
database_id = "de7cb840-101e-42ac-bff9-c2fe7108c66b"

[[durable_objects.bindings]]
name = "NOTIFIER"
class_name = "NotifierDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NotifierDO"]

[[rules]]
type = "Text"
globs = ["**/*.toml"]
